server:
  port: 10009


burny:
  host: 192.168.1.176
  port: 15672
  username: root
  password: root

spring:
  rabbitmq:
    username: root
    password: root
    # host: 192.168.1.176
    host: 192.168.1.128
    port: 5672
    virtual-host: /
    connection-timeout: 20000
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true


